// A história por trás de cada drink. Fatos verificáveis; quando a origem é
// disputada, o texto diz isso com todas as letras ("conta-se que", "há quem
// reivindique") — lenda apresentada como lenda.
//
// Receitas sem verbete aqui recebem a ficha derivada (nível, tempo, ocasião) e,
// se o usuário tiver a IA ativada, a história é escrita sob demanda e guardada.

const HISTORIAS = {
  'negroni': {
    origem: 'Florença, Itália · 1919',
    criador: 'Fosco Scarselli, no Caffè Casoni',
    historia: 'O conde Camillo Negroni voltava de uma temporada nos Estados Unidos com o paladar acostumado a bebidas mais fortes. Pediu ao barman que reforçasse seu Americano de sempre: no lugar da água com gás, gin. Scarselli topou — e trocou também a rodela de limão por uma de laranja, para que todos no salão soubessem, de longe, qual era o copo do conde.',
    curiosidade: 'A casca de laranja não é enfeite: é o crachá do conde, repetido há mais de cem anos no mundo inteiro.',
    ocasiao: 'Aperitivo, fim de tarde',
    temperatura: 'Bem gelado, pedra grande',
    harmoniza: 'Azeitonas, queijo curado, presunto cru',
    variacoes: 'Boulevardier (bourbon), Negroni Sbagliato (espumante)',
    cultura: 'Anthony Bourdain o transformou em bandeira; aparece em <i>Um Lugar ao Sol</i>',
  },
  'daiquiri': {
    origem: 'Cuba · por volta de 1898',
    criador: 'Atribuído a Jennings Cox, engenheiro americano',
    historia: 'Nas minas de ferro de Daiquirí, perto de Santiago de Cuba, engenheiros americanos misturavam o rum local com limão e açúcar para tornar o calor suportável. O nome do vilarejo pegou. Décadas depois, no Floridita de Havana, o drink virou rotina de Hemingway — que o pedia sem açúcar e com o dobro de rum.',
    curiosidade: 'Simples ao ponto da crueldade: com três ingredientes, não há onde esconder um rum ruim ou um limão velho.',
    ocasiao: 'Calor, começo de noite',
    temperatura: 'Gelado, coado sem gelo',
    harmoniza: 'Frutos do mar, ceviche',
    variacoes: 'Hemingway Daiquiri (toranja e maraschino), frozen',
    cultura: 'A bebida de Hemingway em Havana',
  },
  'caipirinha': {
    origem: 'Brasil · registrada por volta de 1918',
    criador: 'Popular, sem autoria',
    historia: 'Conta-se que nasceu no interior paulista como remédio caseiro contra a gripe espanhola: cachaça com limão, alho e mel. O alho e o mel foram ficando pelo caminho; o açúcar e o gelo entraram. A origem é oral e disputada, mas o percurso — de xarope de fazenda a cartão de visita do país — é bem documentado.',
    curiosidade: 'É um dos poucos coquetéis com receita fixada por decreto: o governo brasileiro definiu oficialmente o que pode se chamar caipirinha.',
    ocasiao: 'Churrasco, praia, qualquer sexta-feira',
    temperatura: 'Muito gelada, gelo à vontade',
    harmoniza: 'Petiscos fritos, feijoada, queijo coalho',
    variacoes: 'Caipiroska (vodka), caipifrutas, batida',
    cultura: 'Coquetel nacional do Brasil',
  },
  'mojito': {
    origem: 'Havana, Cuba',
    criador: 'Descende do <i>El Draque</i>, do século XVI',
    historia: 'O ancestral do mojito é o El Draque — aguardente de cana, limão, hortelã e açúcar —, que marinheiros usavam como remédio e cujo nome homenageia o corsário Francis Drake. Com a chegada do rum refinado, virou o mojito moderno. La Bodeguita del Medio o transformou em ponto turístico.',
    curiosidade: 'A famosa placa atribuindo a frase "meu mojito na Bodeguita" a Hemingway é ótima propaganda — e de autenticidade bastante contestada por historiadores.',
    ocasiao: 'Tarde quente, varanda',
    temperatura: 'Gelado, gelo triturado',
    harmoniza: 'Comida cubana, peixe grelhado',
    variacoes: 'Virgin mojito, mojito de frutas',
    cultura: 'Cartão-postal de Havana',
  },
  'old-fashioned': {
    origem: 'Estados Unidos · século XIX',
    criador: 'Reivindicado pelo Pendennis Club, Louisville',
    historia: 'Em 1806, um jornal de Nova York definiu "cocktail" como destilado, açúcar, água e bitters — exatamente esta receita. Quando os drinks começaram a ganhar licores e enfeites, os clientes conservadores passaram a pedir o coquetel "à moda antiga". O apelido virou o nome.',
    curiosidade: 'Não é um drink entre outros: é literalmente a definição original da palavra coquetel, sobrevivendo intacta há dois séculos.',
    ocasiao: 'Noite tranquila, conversa longa',
    temperatura: 'Gelado, uma pedra grande só',
    harmoniza: 'Chocolate amargo, charuto, carne vermelha',
    variacoes: 'Wisconsin Old Fashioned, com rum ou conhaque',
    cultura: 'O copo de Don Draper em <i>Mad Men</i>',
  },
  'manhattan': {
    origem: 'Nova York · anos 1880',
    criador: 'Disputado',
    historia: 'A lenda mais repetida atribui o drink a um banquete no Manhattan Club oferecido por Jennie Jerome, mãe de Winston Churchill — mas as datas não fecham: ela estava na Inglaterra, grávida dele. O que se sabe é que o coquetel apareceu nos bares nova-iorquinos dos anos 1880 e nunca mais saiu.',
    curiosidade: 'É o Old Fashioned que trocou a água por vermute — e, com isso, inventou a família inteira dos coquetéis com vinho aromatizado.',
    ocasiao: 'Antes do jantar, ocasião formal',
    temperatura: 'Mexido com gelo, servido sem',
    harmoniza: 'Queijos azuis, castanhas',
    variacoes: 'Perfect Manhattan, Rob Roy (uísque escocês)',
    cultura: 'Presença constante no cinema noir',
  },
  'martini-seco': {
    origem: 'Estados Unidos · virada do século XX',
    criador: 'Evolução do Martinez',
    historia: 'Começou doce e foi secando década após década: no começo, meio a meio com vermute; nos anos 1950, apenas um sussurro. Churchill dizia bastar olhar para a garrafa de vermute do outro lado do salão. É menos uma receita do que uma discussão de cem anos sobre proporção.',
    curiosidade: 'Bond pede batido, não mexido — e todo bartender range os dentes: bater quebra o gelo e turva a bebida, que deveria ser límpida como cristal.',
    ocasiao: 'Aperitivo, ocasião elegante',
    temperatura: 'Gélido, taça congelada',
    harmoniza: 'Azeitona, ostras, amêndoas salgadas',
    variacoes: 'Dirty, Gibson (cebolinha), Vesper',
    cultura: 'A assinatura de James Bond',
  },
  'gin-tonica': {
    origem: 'Índia colonial britânica · século XIX',
    criador: 'Oficiais do exército britânico',
    historia: 'A água tônica nasceu remédio: quinino contra a malária, amargo a ponto de ser intragável. Os oficiais britânicos passaram a cortá-la com gin, açúcar e limão. O remédio virou ritual — e o ritual, um dos coquetéis mais bebidos do planeta.',
    curiosidade: 'Churchill brincava que o gin com tônica salvou mais vidas de ingleses do que todos os médicos do Império.',
    ocasiao: 'Qualquer hora, calor',
    temperatura: 'Muito gelado, taça cheia de gelo',
    harmoniza: 'Petiscos leves, frutos do mar',
    variacoes: 'Gin tônica com especiarias, com frutas cítricas',
    cultura: 'Renasceu nos anos 2000 pela mão dos bares espanhóis',
  },
  'moscow-mule': {
    origem: 'Los Angeles, EUA · 1941',
    criador: 'John G. Martin e Jack Morgan',
    historia: 'Três estoques encalhados num só balcão: um importador com vodka que ninguém queria, um dono de bar com ginger beer parada e uma sócia com canecas de cobre sem saída. Juntaram os três no Cock\'n Bull, saíram fotografando o drink pelos bares da cidade — e criaram, de quebra, o gosto americano por vodka.',
    curiosidade: 'A caneca de cobre não é frescura: o metal transmite o frio rápido e mantém a bebida gelada por muito mais tempo.',
    ocasiao: 'Happy hour, calor',
    temperatura: 'Muito gelado, caneca gelada',
    harmoniza: 'Comida apimentada, tacos',
    variacoes: 'Mule com gin, com uísque, com tequila',
    cultura: 'Uma das campanhas de marketing mais bem-sucedidas do século',
  },
  'espresso-martini': {
    origem: 'Londres · fim dos anos 1980',
    criador: 'Dick Bradsell',
    historia: 'Uma modelo chegou ao balcão onde Bradsell trabalhava e pediu algo que a acordasse e depois a derrubasse. Ele tinha uma máquina de espresso ao lado do bar. Nascia — com outro nome, Vodka Espresso — o coquetel que quarenta anos depois tomaria as cartas do mundo inteiro.',
    curiosidade: 'A espuma não vem de clara nem de creme: são os óleos do café, emulsionados pela batida vigorosa. Café velho não faz espuma.',
    ocasiao: 'Depois do jantar, antes da noite começar',
    temperatura: 'Gelado, taça sem gelo',
    harmoniza: 'Sobremesa de chocolate, tiramisù',
    variacoes: 'Com licor de avelã, com tequila',
    cultura: 'O coquetel-símbolo da retomada dos bares nos anos 2020',
  },
  'bramble': {
    origem: 'Londres · 1984',
    criador: 'Dick Bradsell, no Fred\'s Club',
    historia: 'Bradsell queria um drink que fosse inglês de verdade, sem parecer importado. Voltou à infância na Ilha de Wight, às tardes colhendo amoras silvestres no mato, e desenhou o gosto daquilo: gin, limão, açúcar e um fio de licor de amora sangrando pelo gelo triturado.',
    curiosidade: 'O licor é despejado por cima de propósito, sem misturar — o desenho vermelho descendo pelo gelo é parte da receita.',
    ocasiao: 'Tarde de verão',
    temperatura: 'Gelado, gelo triturado',
    harmoniza: 'Sobremesas de frutas vermelhas',
    variacoes: 'Com uísque, com frutas da estação',
    cultura: 'Um dos primeiros "clássicos modernos" reconhecidos',
  },
  'pina-colada': {
    origem: 'San Juan, Porto Rico · 1954',
    criador: 'Ramón "Monchito" Marrero, no Caribe Hilton',
    historia: 'Marrero passou três meses testando combinações até chegar ao ponto: queria um drink que resumisse a ilha inteira em um copo. Serviu-o por 35 anos no mesmo hotel. Em 1978, Porto Rico o declarou bebida oficial do país.',
    curiosidade: 'O nome descreve a receita: <i>piña</i> (abacaxi) <i>colada</i> (coada) — o suco de abacaxi espremido e passado na peneira.',
    ocasiao: 'Praia, piscina, férias',
    temperatura: 'Gelado, batido com gelo',
    harmoniza: 'Frutas tropicais, camarão empanado',
    variacoes: 'Chi Chi (vodka), versão sem álcool',
    cultura: 'Imortalizada na canção <i>Escape</i>, de Rupert Holmes',
  },
  'irish-coffee': {
    origem: 'Foynes, Irlanda · 1943',
    criador: 'Joe Sheridan',
    historia: 'Um voo transatlântico voltou ao aeroporto por causa do tempo ruim, e os passageiros desembarcaram encharcados e congelando de madrugada. O chef Sheridan improvisou café com uísque e creme por cima. Um americano perguntou se aquilo era café brasileiro; ele respondeu que era café irlandês.',
    curiosidade: 'O creme tem que ser levemente batido e boiar: bebe-se o café quente <i>através</i> da camada fria de creme — o contraste é o drink.',
    ocasiao: 'Noite fria, depois do jantar',
    temperatura: 'Quente, com creme frio por cima',
    harmoniza: 'Sobremesas, torta de maçã',
    variacoes: 'Com conhaque, com licor de café',
    cultura: 'Cruzou o Atlântico em 1952 e virou instituição em São Francisco',
  },
  'aperol-spritz': {
    origem: 'Vêneto, Itália',
    criador: 'Herança austríaca, batizada em Pádua',
    historia: 'Quando o Vêneto pertencia ao império austríaco, os soldados achavam o vinho local forte demais e pediam um esguicho — <i>spritzen</i> — de água. O costume ficou. Em 1919, os irmãos Barbieri criaram o Aperol em Pádua, e a Itália juntou as duas heranças no copo.',
    curiosidade: 'Monta-se pela ordem inversa da intuição: espumante primeiro, Aperol depois — assim ele desce e colore a bebida sozinho.',
    ocasiao: 'Aperitivo, fim de tarde ao ar livre',
    temperatura: 'Muito gelado, taça cheia de gelo',
    harmoniza: 'Azeitonas, batatinhas, presunto de Parma',
    variacoes: 'Spritz com Campari, Hugo, Select',
    cultura: 'O som do verão europeu',
  },
  'cosmopolitan': {
    origem: 'Estados Unidos · anos 1980',
    criador: 'Disputado; consagrado por Dale DeGroff',
    historia: 'Várias pessoas reivindicam a criação — de Miami a São Francisco. O que não se discute é quem o tornou mundial: Dale DeGroff o serviu no Rainbow Room, em Nova York, e a televisão fez o resto nos anos 1990.',
    curiosidade: 'Sofreu a pior das vinganças do sucesso: virou tão onipresente que os bares passaram a ter vergonha dele. Feito com limão espremido na hora, é excelente.',
    ocasiao: 'Noite, encontro com amigos',
    temperatura: 'Gelado, taça sem gelo',
    harmoniza: 'Canapés, salmão defumado',
    variacoes: 'Com frutas vermelhas, versão seca',
    cultura: 'A marca registrada de <i>Sex and the City</i>',
  },
  'penicillin': {
    origem: 'Nova York · 2005',
    criador: 'Sam Ross, no Milk & Honey',
    historia: 'Ross pegou a lógica de um remédio caseiro de avó — mel, limão e gengibre — e o levou a sério, com uísque escocês na base e um fio de single malt defumado por cima. O nome é piada e diagnóstico ao mesmo tempo.',
    curiosidade: 'É considerado um dos poucos drinks criados neste século que já entrou no cânone dos clássicos, ao lado de receitas centenárias.',
    ocasiao: 'Noite fria, quando a garganta pede',
    temperatura: 'Gelado, pedra grande',
    harmoniza: 'Queijos defumados, castanhas',
    variacoes: 'Com bourbon, com mel de flores',
    cultura: 'Clássico moderno instantâneo',
  },
  'tom-collins': {
    origem: 'Nova York · 1874',
    criador: 'Batizado por uma pegadinha',
    historia: 'Em 1874 espalhou-se por Nova York uma brincadeira: dizia-se a alguém que um tal Tom Collins estava num bar da esquina falando mal dele. A vítima saía furiosa procurando o sujeito de bar em bar. Os bartenders, espertos, criaram um drink com o nome — para servir a quem chegasse perguntando.',
    curiosidade: 'É provavelmente o único coquetel clássico que existe por causa de uma piada coletiva que tomou uma cidade inteira.',
    ocasiao: 'Tarde quente, jardim',
    temperatura: 'Gelado, copo alto com gelo',
    harmoniza: 'Petiscos leves, saladas',
    variacoes: 'John Collins (uísque), Vodka Collins',
    cultura: 'O "Great Tom Collins Hoax" de 1874',
  },
  'french-75': {
    origem: 'Paris · 1915',
    criador: 'Atribuído a Harry MacElhone',
    historia: 'Batizado em plena Primeira Guerra com o nome do canhão francês de 75 milímetros, o mais temido da artilharia aliada. Diziam que o efeito da bebida lembrava levar um tiro da peça — gim e champanhe fazem mesmo um estrago elegante.',
    curiosidade: 'É um dos raros clássicos que sobem: começa como um sour comum e termina com champanhe, mudando de textura no meio do gole.',
    ocasiao: 'Celebração, brinde',
    temperatura: 'Muito gelado, taça flute',
    harmoniza: 'Ostras, canapés, queijos frescos',
    variacoes: 'French 76 (vodka), com conhaque',
    cultura: 'Aparece em <i>Casablanca</i>',
  },
  'bellini': {
    origem: 'Veneza, Itália · 1948',
    criador: 'Giuseppe Cipriani, no Harry\'s Bar',
    historia: 'Cipriani fazia purê de pêssegos brancos e o misturava ao prosecco. O tom rosado da bebida lembrou-lhe a toga de um santo num quadro de Giovanni Bellini, pintor veneziano do século XV, então em exposição na cidade. O nome ficou.',
    curiosidade: 'A receita original exige pêssego branco, não amarelo — a diferença de perfume é o motivo de o drink existir.',
    ocasiao: 'Brunch, comemoração',
    temperatura: 'Gelado, taça flute',
    harmoniza: 'Café da manhã, frutas, presunto cru',
    variacoes: 'Rossini (morango), Mimosa (laranja)',
    cultura: 'O Harry\'s Bar de Veneza é monumento nacional italiano',
  },
  'bloody-mary': {
    origem: 'Paris · anos 1920',
    criador: 'Fernand Petiot, no Harry\'s New York Bar',
    historia: 'Petiot começou misturando partes iguais de vodka e suco de tomate em Paris. Levou a receita para o St. Regis, em Nova York, onde foi obrigado a rebatizá-la de Red Snapper por pudor do hotel — mas o nome original venceu.',
    curiosidade: 'É o único clássico que se tempera como um prato: sal, pimenta, molho inglês, tabasco. Cada bartender tem sua receita secreta de tempero.',
    ocasiao: 'Brunch, domingo de manhã',
    temperatura: 'Gelado, copo alto',
    harmoniza: 'Ovos, bacon, frutos do mar',
    variacoes: 'Red Snapper (gin), Michelada (cerveja)',
    cultura: 'Fama imortal de cura para ressaca',
  },
  'sidecar': {
    origem: 'Paris ou Londres · anos 1920',
    criador: 'Disputado entre Harry MacElhone e Pat MacGarry',
    historia: 'Conta-se que um cliente habitual chegava ao bar no sidecar da motocicleta de seu motorista, sempre no fim da tarde, e pedia algo que o esquentasse antes do jantar. O apelido do veículo virou o nome da bebida.',
    curiosidade: 'A borda de açúcar divide bartenders há um século: metade jura que é essencial, a outra metade que é heresia sobre um drink já equilibrado.',
    ocasiao: 'Antes do jantar, noite fria',
    temperatura: 'Gelado, taça sem gelo',
    harmoniza: 'Queijos maturados, sobremesas cítricas',
    variacoes: 'Com rum, com bourbon',
    cultura: 'Ícone da Paris dos anos 1920',
  },
  'rabo-de-galo': {
    origem: 'Brasil · anos 1950',
    criador: 'Popular, de boteco',
    historia: 'Nasceu simples como só o boteco brasileiro sabe: cachaça e vermute, na medida do olho. Ganhou fama com a chegada dos aperitivos amargos italianos ao país e virou o aperitivo nacional — barato, direto e sem cerimônia.',
    curiosidade: '"Rabo de galo" é a tradução literal de <i>cocktail</i>. O Brasil batizou seu coquetel simplesmente de "coquetel".',
    ocasiao: 'Fim de tarde, boteco',
    temperatura: 'Gelado, copo baixo',
    harmoniza: 'Petiscos de boteco, torresmo, queijo',
    variacoes: 'Com Cynar, com licor de ervas',
    cultura: 'Redescoberto pela nova coquetelaria brasileira',
  },
  'boulevardier': {
    origem: 'Paris · anos 1920',
    criador: 'Erskine Gwynne',
    historia: 'Gwynne era um americano rico que editava em Paris uma revista literária chamada <i>The Boulevardier</i>. Frequentava o Harry\'s Bar e pedia seu Negroni com bourbon no lugar do gin. Harry MacElhone anotou a variação em seu livro com o nome da revista.',
    curiosidade: 'A troca parece pequena, mas muda tudo: o bourbon adoça e arredonda o amargo do Campari que o gin deixava afiado.',
    ocasiao: 'Noite fria, conversa longa',
    temperatura: 'Gelado, pedra grande',
    harmoniza: 'Carnes vermelhas, chocolate amargo',
    variacoes: 'Old Pal (mais seco), com centeio',
    cultura: 'O Negroni do inverno',
  },
  'cuba-libre': {
    origem: 'Havana, Cuba · por volta de 1900',
    criador: 'Soldados e cubanos no pós-guerra',
    historia: 'Depois da guerra hispano-americana, a Coca-Cola chegou a Cuba junto com as tropas americanas. Rum cubano, refrigerante americano e um brinde que era palavra de ordem política: "¡Por Cuba libre!" — por Cuba livre.',
    curiosidade: 'Sem o limão espremido não é Cuba Libre, é rum com Coca-Cola. A acidez é o que separa os dois.',
    ocasiao: 'Festa, encontro informal',
    temperatura: 'Gelado, copo alto',
    harmoniza: 'Comida de festa, petiscos fritos',
    variacoes: 'Com rum escuro, com limão siciliano',
    cultura: 'Um brinde político que virou bebida',
  },
  'margarita': {
    origem: 'Fronteira México–Estados Unidos · anos 1930–40',
    criador: 'Disputado: ao menos quatro pessoas reivindicam a autoria',
    historia: 'Há quem credite a Carlos "Danny" Herrera, em Tijuana, que teria adaptado o drink para uma cliente alérgica a todo destilado que não fosse tequila. Outros apontam Margarita Sames, socialite do Texas, em Acapulco. Uma terceira hipótese é mais prosaica e talvez a mais provável: a Margarita seria simplesmente o Daisy — <i>margarita</i> em espanhol — feito com tequila no lugar do conhaque.',
    curiosidade: 'A borda de sal existe por função, não por enfeite: o sal suprime o amargor e faz a acidez do limão parecer mais doce. Sale metade da borda e o bebedor escolhe cada gole.',
    ocasiao: 'Começo de noite, comida mexicana',
    temperatura: 'Bem gelada, coada sem gelo ou com gelo novo',
    harmoniza: 'Tacos, guacamole, ceviche, pimenta',
    variacoes: 'Tommy\'s (agave no lugar do licor), frozen, picante',
    cultura: 'O coquetel de tequila mais pedido do mundo',
  },
  'whiskey-sour': {
    origem: 'Registrado em 1862, no livro de Jerry Thomas',
    criador: 'Fórmula dos marinheiros britânicos',
    historia: 'A família dos <i>sours</i> nasceu no mar: destilado, cítrico e açúcar era a ração que a Marinha britânica usava contra o escorbuto nas travessias longas. Em terra firme e com uísque no lugar do rum, virou coquetel de balcão. Jerry Thomas o imprimiu em 1862, no primeiro livro de bar da história.',
    curiosidade: 'A clara de ovo não entra por sabor — ela quase não tem. Entra pela textura: a espuma segura os aromas junto do nariz e arredonda a aspereza do álcool.',
    ocasiao: 'Fim de tarde, conversa sem pressa',
    temperatura: 'Gelado, coado sem gelo',
    harmoniza: 'Castanhas, queijos, comida defumada',
    variacoes: 'New York Sour (vinho tinto por cima), Boston Sour, Amaretto Sour',
    cultura: 'A receita-mãe: quem entende o sour entende metade da coquetelaria',
  },
  'gimlet': {
    origem: 'Marinha britânica · fim do século XIX',
    criador: 'Atribuído ao médico naval Thomas Gimlette',
    historia: 'Conta-se que o cirurgião-mor Gimlette misturava o suco de limão obrigatório contra o escorbuto com a ração de gin dos oficiais, para que a tripulação tomasse o remédio sem reclamar. A atribuição é tradicional e nunca foi comprovada; o que é documentado é que o cordial de limão engarrafado, criado justamente para durar em alto-mar, tornou o drink possível a bordo.',
    curiosidade: 'O Gimlete clássico não leva limão fresco, e sim cordial — mais doce e mais denso. Trocar por limão fresco faz outro drink, bom, mas outro.',
    ocasiao: 'Aperitivo, noite tranquila',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Ostras, peixe cru, batata frita com sal grosso',
    variacoes: 'Com vodka, com pepino, Southside (com hortelã)',
    cultura: 'Drink de Philip Marlowe em <i>O Longo Adeus</i>, de Raymond Chandler',
  },
  'americano': {
    origem: 'Milão, Itália · anos 1860',
    criador: 'Bar de Gaspare Campari',
    historia: 'Nasceu como <i>Milano-Torino</i> — Campari de Milão, vermute de Turim. Ganhou o nome atual no início do século XX, quando virou o pedido preferido dos americanos em Milão; há quem diga que o apelido veio dos que fugiam da Lei Seca. A água com gás foi a última a chegar, e é ela que faz do drink um aperitivo e não um digestivo.',
    curiosidade: 'É o pai do Negroni: troque a água com gás por gin e você tem o filho mais famoso.',
    ocasiao: 'Aperitivo, tarde de calor',
    temperatura: 'Muito gelado, copo alto',
    harmoniza: 'Azeitonas, batata frita, focaccia',
    variacoes: 'Negroni (com gin), Negroni Sbagliato (com espumante)',
    cultura: 'O primeiro drink que James Bond pede nos livros de Ian Fleming',
  },
  'paloma': {
    origem: 'México · meados do século XX',
    criador: 'Popular, sem autoria firmada',
    historia: 'No México se bebe muito mais Paloma do que Margarita. A combinação de tequila com refrigerante de toranja é de cantina: prática, barata e feita para o calor. A popularização acompanha a chegada dos refrigerantes de toranja engarrafados ao país, nos anos 1950.',
    curiosidade: 'O sal na borda faz aqui o trabalho oposto ao da Margarita: em vez de domar a acidez, ele corta o amargo da toranja e deixa o doce aparecer.',
    ocasiao: 'Tarde quente, churrasco, praia',
    temperatura: 'Muito gelada, copo alto com bastante gelo',
    harmoniza: 'Tacos, carne grelhada, comida apimentada',
    variacoes: 'Com toranja fresca e água com gás, com mezcal',
    cultura: 'O drink de tequila que o México realmente bebe',
  },
  'tequila-sunrise': {
    origem: 'Sausalito, Califórnia · 1972',
    criador: 'Bobby Lozoff e Billy Rice, no Trident',
    historia: 'A versão moderna nasceu no bar Trident, na Califórnia. Ganhou o mundo quando os Rolling Stones a adotaram na turnê americana de 1972 — a mesma que a banda passou a chamar de "Cocaine and Tequila Sunrise Tour". Existiu um Tequila Sunrise anterior, dos anos 1930, com licor de cássis e limão, que é outra bebida.',
    curiosidade: 'O degradê não é truque de bar: a grenadine é mais densa que o suco e afunda sozinha. Por isso ela entra por último e sem mexer — mexer apaga o amanhecer.',
    ocasiao: 'Piscina, brunch, festa de dia',
    temperatura: 'Gelado, copo alto',
    harmoniza: 'Frutas, petiscos leves',
    variacoes: 'Tequila Sunset (com cassis), com espumante',
    cultura: 'Batizou uma canção dos Eagles e uma turnê dos Rolling Stones',
  },
  'dark-n-stormy': {
    origem: 'Bermudas · início do século XX',
    criador: 'Ligado à cervejaria da Marinha Real britânica',
    historia: 'A ginger beer chegou às Bermudas pelas mãos da Marinha britânica; o rum escuro local, Gosling\'s, já estava lá. O nome vem da cor: conta-se que um marinheiro descreveu a camada escura de rum flutuando sobre o dourado como "a nuvem que só um louco navegaria por baixo".',
    curiosidade: 'É um dos raríssimos coquetéis com marca registrada: nas Bermudas, o nome pertence legalmente à Gosling\'s, e feito com outro rum ele oficialmente não pode se chamar assim.',
    ocasiao: 'Fim de tarde, dia nublado, barco',
    temperatura: 'Gelado, copo alto com bastante gelo',
    harmoniza: 'Frutos do mar, comida apimentada, gengibre',
    variacoes: 'Moscow Mule (vodka), com limão siciliano',
    cultura: 'Bebida nacional das Bermudas',
  },
  'clover-club': {
    origem: 'Filadélfia, Estados Unidos · antes de 1917',
    criador: 'Clover Club, sociedade que se reunia no Bellevue-Stratford',
    historia: 'O nome é de um clube de advogados, jornalistas e empresários que jantava no hotel Bellevue-Stratford. O drink era o deles. Sumiu do mapa depois da Lei Seca, quando coquetéis com clara de ovo passaram a soar antiquados, e só voltou nos anos 2000, com o resgate da coquetelaria clássica.',
    curiosidade: 'O rosa vem de framboesa de verdade, não de corante — e por décadas isso bastou para o drink ser injustamente tratado como bebida sem seriedade.',
    ocasiao: 'Aperitivo, ocasião especial',
    temperatura: 'Gelado, taça sem gelo',
    harmoniza: 'Queijos frescos, torradas, frutas vermelhas',
    variacoes: 'Pink Lady (com gim e granadina), com morango',
    cultura: 'Símbolo da coquetelaria pré-Lei Seca redescoberta',
  },
  'white-russian': {
    origem: 'Registrado nos anos 1960',
    criador: 'Derivado do Black Russian, dos anos 1940',
    historia: 'O Black Russian foi criado em 1949, em Bruxelas, pelo barman Gustave Tops, para a embaixadora americana Perle Mesta — "russo" pela vodka, em plena Guerra Fria. Acrescentar creme veio depois, e o resultado ficou obscuro por décadas.',
    curiosidade: 'Deve quase toda a fama atual a um único filme: <i>O Grande Lebowski</i>, de 1998. O Dude toma nove deles ao longo da história, e o drink saiu do esquecimento por causa disso.',
    ocasiao: 'Depois do jantar, noite tranquila',
    temperatura: 'Gelado, copo baixo com gelo',
    harmoniza: 'Sobremesas de chocolate, café',
    variacoes: 'Black Russian (sem creme), com leite, com sorvete',
    cultura: 'A bebida do Dude em <i>O Grande Lebowski</i>',
  },
  'black-russian': {
    origem: 'Bruxelas, Bélgica · 1949',
    criador: 'Gustave Tops, no Hotel Metropole',
    historia: 'Tops criou o drink para Perle Mesta, embaixadora dos Estados Unidos na Bélgica. O nome junta a vodka ao clima da época: era o começo da Guerra Fria, e chamar de "russo" qualquer coisa feita com vodka era quase automático.',
    curiosidade: 'Dois ingredientes, nenhuma técnica, nenhum cítrico para corrigir erro. O equilíbrio depende inteiramente da proporção — e é por isso que ele é mais difícil do que parece.',
    ocasiao: 'Digestivo, fim de noite',
    temperatura: 'Gelado, copo baixo com gelo',
    harmoniza: 'Chocolate amargo, café, sobremesas',
    variacoes: 'White Russian (com creme), com cold brew',
    cultura: 'Um coquetel batizado pela Guerra Fria',
  },
  'sex-on-the-beach': {
    origem: 'Flórida, Estados Unidos · anos 1980',
    criador: 'Atribuído a um bar de Fort Lauderdale',
    historia: 'Conta-se que nasceu na temporada de férias universitárias de 1987, quando um bar da Flórida precisava vender o estoque de licor de pêssego e schnapps. O nome escandaloso era a estratégia de venda, e funcionou: virou o retrato líquido dos anos 1980.',
    curiosidade: 'A camada vermelha no fundo não é grenadine: é o cranberry, mais denso que o suco de laranja, se acomodando sozinho.',
    ocasiao: 'Praia, piscina, festa',
    temperatura: 'Bem gelado, copo alto',
    harmoniza: 'Petiscos leves, frutas',
    variacoes: 'Com vodka de frutas, sem álcool com sucos',
    cultura: 'O coquetel que resume os anos 1980',
  },
  'mimosa': {
    origem: 'Paris, França · 1925',
    criador: 'Frank Meier, no bar do Hotel Ritz',
    historia: 'Meier registrou a receita no Ritz em 1925. O nome vem da flor de mimosa, pelo amarelo. Existe um parente mais velho e quase idêntico, o Buck\'s Fizz, criado em Londres em 1921, que leva mais espumante e menos suco.',
    curiosidade: 'É um dos poucos drinks em que o suco vem antes: coloca-se o suco e completa-se com o espumante, nunca ao contrário, ou a espuma transborda a taça.',
    ocasiao: 'Café da manhã tardio, comemoração, casamento',
    temperatura: 'Muito gelada, taça flute',
    harmoniza: 'Ovos, salmão defumado, croissant, brunch',
    variacoes: 'Buck\'s Fizz, Bellini (pêssego), com toranja',
    cultura: 'Instituição do brunch no mundo inteiro',
  },
  'kir-royale': {
    origem: 'Borgonha, França · anos 1940',
    criador: 'Batizado em homenagem ao cônego Félix Kir',
    historia: 'Félix Kir foi herói da Resistência e prefeito de Dijon por mais de vinte anos. Servia vinho branco com creme de cassis nas recepções da cidade — os dois produtos típicos da Borgonha, juntos por motivo político e econômico. O Kir Royale troca o vinho branco por champanhe.',
    curiosidade: 'O cassis existia ali para salvar vinhos brancos ácidos demais. O que era conserto virou clássico.',
    ocasiao: 'Aperitivo, comemoração',
    temperatura: 'Muito gelado, taça flute',
    harmoniza: 'Canapés, queijos suaves, frutas vermelhas',
    variacoes: 'Kir (com vinho branco), Kir Impérial (framboesa)',
    cultura: 'Um prefeito francês que virou nome de aperitivo',
  },
  'sangria': {
    origem: 'Península Ibérica · tradição antiga, nome do século XVIII',
    criador: 'Popular, sem autoria',
    historia: 'Diluir vinho com água, especiarias e frutas é hábito antigo no Mediterrâneo — em parte porque a água nem sempre era segura de beber pura. O nome vem de <i>sangre</i>, pela cor. Ganhou o mundo na Feira Mundial de Nova York, em 1964, onde o pavilhão espanhol a serviu para multidões.',
    curiosidade: 'É um dos poucos drinks que melhoram esperando: as frutas precisam de horas na geladeira para trocar sabor com o vinho. Sangria feita na hora é vinho com fruta boiando.',
    ocasiao: 'Almoço longo, mesa cheia, verão',
    temperatura: 'Gelada, jarra com gelo',
    harmoniza: 'Paella, tapas, embutidos, churrasco',
    variacoes: 'Sangria branca, de espumante, de frutas vermelhas',
    cultura: 'Na União Europeia, só Espanha e Portugal podem vendê-la com esse nome',
  },
  'caipiroska': {
    origem: 'Brasil · anos 1990',
    criador: 'Popular, sem autoria',
    historia: 'Filha direta da caipirinha, nasceu quando a vodka se popularizou nos bares brasileiros e uma parte do público quis a mesma bebida sem o gosto marcante da cachaça. O nome é uma piada com a terminação russa — e pegou.',
    curiosidade: 'Por ser mais neutra, ela perdoa menos: sem o caráter da cachaça para disfarçar, um limão maltratado ou o miolo branco amargo aparecem no copo.',
    ocasiao: 'Encontro informal, calor',
    temperatura: 'Muito gelada, gelo à vontade',
    harmoniza: 'Petiscos, comida de boteco',
    variacoes: 'Com frutas vermelhas, com kiwi, com saquê (caipisaquê)',
    cultura: 'A prova de que a caipirinha virou fôrma, não receita',
  },
  'caipifruta-morango': {
    origem: 'Brasil · popularizada nos anos 1990',
    criador: 'Popular, sem autoria',
    historia: 'A caipifruta é o que acontece quando um país de fruta boa e barata resolve aplicar a fórmula da caipirinha a tudo que houver na feira. Morango, maracujá, kiwi, abacaxi, caju: o método é sempre o mesmo — macerar, adoçar, gelar.',
    curiosidade: 'O açúcar aqui não serve só para adoçar: ele age como abrasivo na maceração e ajuda a romper a fruta, extraindo suco e aroma que a colher sozinha não tiraria.',
    ocasiao: 'Verão, praia, encontro em casa',
    temperatura: 'Muito gelada, copo cheio de gelo',
    harmoniza: 'Queijo coalho, petiscos, sobremesas',
    variacoes: 'Com qualquer fruta da estação, com vodka, com saquê',
    cultura: 'Cardápio obrigatório de quiosque brasileiro',
  },
  'batida-de-coco': {
    origem: 'Brasil · tradição popular',
    criador: 'Popular, sem autoria',
    historia: 'A batida é uma família inteira da coquetelaria brasileira: cachaça batida com leite condensado e alguma fruta ou castanha. A de coco é a mais conhecida e a mais festeira — presença garantida em festa junina, casamento de interior e véspera de ano-novo.',
    curiosidade: 'O leite condensado faz aqui trabalho duplo: adoça e emulsiona. É ele que segura a cachaça e o leite de coco juntos, sem separar no copo.',
    ocasiao: 'Festa, festa junina, fim de ano',
    temperatura: 'Muito gelada, batida com gelo',
    harmoniza: 'Bolos, doces de festa, milho, amendoim',
    variacoes: 'De maracujá, de amendoim, de leite ninho',
    cultura: 'Coquetelaria de festa brasileira, sem cerimônia',
  },
  'hugo-spritz': {
    origem: 'Tirol do Sul, Itália · 2005',
    criador: 'Roland Gruber, em Naturno',
    historia: 'Gruber queria uma alternativa mais leve ao Aperol Spritz e testou primeiro com xarope de melissa. O nome, contou depois, foi escolhido quase ao acaso. A troca para flor de sabugueiro — que cresce por toda a região alpina — é o que fez o drink pegar, primeiro no norte da Itália e na Áustria, depois no resto do mundo.',
    curiosidade: 'É dos poucos clássicos com data e autor conhecidos e ainda vivo para contar a história — a maioria dos coquetéis famosos tem origem disputada justamente por ser antiga demais.',
    ocasiao: 'Aperitivo, tarde de calor, ao ar livre',
    temperatura: 'Muito gelado, taça grande com bastante gelo',
    harmoniza: 'Queijos frescos, saladas, aperitivos leves',
    variacoes: 'Aperol Spritz, com pepino, sem álcool',
    cultura: 'O spritz que conquistou os Alpes antes da Itália inteira',
  },
  'virgin-mojito': {
    origem: 'Versão sem álcool do mojito cubano',
    criador: 'Popular, sem autoria',
    historia: 'O mojito descende do Draque, remédio do século XVI feito com aguardente de cana, limão e hortelã para tratar doenças de bordo. Tirado o destilado, sobra exatamente o que sempre fez o drink funcionar: hortelã, limão, açúcar e gás.',
    curiosidade: 'A hortelã se bate de leve, nunca se soca. Rasgar a folha libera clorofila e amargo; a ideia é só machucar o suficiente para soltar o óleo aromático.',
    ocasiao: 'Calor, tarde, para quem não bebe',
    temperatura: 'Muito gelado, copo alto com gelo picado',
    harmoniza: 'Comida leve, frutos do mar, saladas',
    variacoes: 'Com frutas vermelhas, com pepino, com maracujá',
    cultura: 'Prova de que sem álcool não precisa ser refrigerante',
  },
  'shirley-temple': {
    origem: 'Estados Unidos · anos 1930',
    criador: 'Disputado entre bares de Hollywood e Palm Springs',
    historia: 'Criado para que a atriz-mirim Shirley Temple tivesse o que brindar em jantares de adultos. Ela nunca gostou: em entrevistas já adulta, chamou o drink de enjoativo e reclamou de nunca ter recebido nada por ele — chegou a processar empresas que engarrafaram a bebida com seu nome.',
    curiosidade: 'É o avô de toda a categoria dos <i>mocktails</i>: o primeiro drink sem álcool pensado para ser servido como coquetel, com copo e cuidado próprios.',
    ocasiao: 'Festa de criança, para quem não bebe',
    temperatura: 'Gelado, copo alto',
    harmoniza: 'Bolo, petiscos doces',
    variacoes: 'Roy Rogers (com cola), com ginger ale',
    cultura: 'A atriz mais famosa da infância de Hollywood virou bebida',
  },
  'limonada-suica': {
    origem: 'Brasil · nome sem relação com a Suíça',
    criador: 'Popular, sem autoria',
    historia: 'Não é suíça e não é bem limonada: é o limão inteiro, com casca, batido rapidamente e coado, com leite condensado. A origem do nome é obscura — a hipótese mais repetida é que "suíça" tenha virado sinônimo de cremoso, pela associação com o creme de leite suíço.',
    curiosidade: 'Bater por muito tempo estraga tudo: a casca solta o amargo em segundos. Pulsa-se o liquidificador e coa-se na hora — quem bate meio minuto a mais serve uma bebida amarga.',
    ocasiao: 'Almoço, tarde de calor',
    temperatura: 'Muito gelada, batida com bastante gelo',
    harmoniza: 'Comida caseira, feijoada, frituras',
    variacoes: 'Com leite de coco, sem leite condensado, com hortelã',
    cultura: 'Presença fixa no cardápio de restaurante brasileiro',
  },
  'abacaxi-hortela': {
    origem: 'Brasil · combinação de feira',
    criador: 'Popular, sem autoria',
    historia: 'Não tem certidão de nascimento nem inventor: é o encontro de duas coisas que o Brasil tem em abundância e que se completam sozinhas. O abacaxi traz açúcar e acidez na mesma mordida; a hortelã traz o frescor que impede o doce de cansar.',
    curiosidade: 'O abacaxi contém bromelina, uma enzima que digere proteína — é o mesmo motivo de arder a boca quando se come muito e de a fruta não firmar gelatina.',
    ocasiao: 'Calor, café da manhã, depois de treinar',
    temperatura: 'Muito gelado, batido com gelo',
    harmoniza: 'Comida leve, frutas, saladas',
    variacoes: 'Com gengibre, com limão, com água de coco',
    cultura: 'Clássico de casa, não de bar',
  },
  'maracuja-tonica': {
    origem: 'Coquetelaria brasileira contemporânea',
    criador: 'Popular, de bar',
    historia: 'Nasceu do gosto brasileiro pela água tônica com fruta, na esteira da moda das gin-tônicas autorais dos anos 2010. Tirado o gin, o que sobra tem estrutura suficiente para se sustentar: o amargo do quinino faz o papel que o destilado faria.',
    curiosidade: 'O quinino da tônica é o mesmo composto usado contra a malária, e é ele que dá o amargo. Sem álcool, é o amargo que impede a bebida de virar suco doce.',
    ocasiao: 'Aperitivo sem álcool, tarde de calor',
    temperatura: 'Muito gelada, taça com bastante gelo',
    harmoniza: 'Petiscos, queijos, comida apimentada',
    variacoes: 'Com alecrim, com gengibre, com pimenta rosa',
    cultura: 'A resposta de bar a quem não bebe e não quer refrigerante',
  },
  'mai-tai': {
    origem: 'Oakland, Estados Unidos · 1944',
    criador: 'Victor "Trader Vic" Bergeron',
    historia: 'Bergeron contou que serviu a mistura a amigos taitianos e que um deles provou e disse "Maita\'i roa ae" — algo como "isto é muito bom". O nome ficou. Donn Beach, do Don the Beachcomber, reivindicou a autoria a vida inteira; a disputa nunca foi resolvida.',
    curiosidade: 'O Mai Tai original não leva abacaxi nem suco de laranja. A versão açucarada de resort é uma deturpação dos anos 1960 — o drink de verdade é seco, amargo de amêndoa e bem mais sério.',
    ocasiao: 'Verão, fim de tarde, festa tiki',
    temperatura: 'Gelado, gelo picado até a borda',
    harmoniza: 'Comida asiática, porco, frutos do mar grelhados',
    variacoes: 'Com falernum, Royal Hawaiian, sem o rum escuro por cima',
    cultura: 'Símbolo da cultura tiki americana do pós-guerra',
  },
  'jungle-bird': {
    origem: 'Kuala Lumpur, Malásia · 1978',
    criador: 'Aviary Bar, do Hilton Kuala Lumpur',
    historia: 'Nasceu como drink de boas-vindas do hotel, servido num copo de cerâmica em forma de pássaro. Ficou esquecido por trinta anos até Jeff "Beachbum" Berry resgatá-lo num livro de 2002, e desde então virou o tiki preferido de quem não gosta de tiki.',
    curiosidade: 'É o único clássico tropical que usa Campari. O amargo italiano corta a doçura do abacaxi e é exatamente por isso que o drink não enjoa no terceiro gole.',
    ocasiao: 'Calor, aperitivo, festa',
    temperatura: 'Gelado, gelo novo',
    harmoniza: 'Comida apimentada, amendoim, comida tailandesa',
    variacoes: 'Com rum da Jamaica, com Aperol no lugar do Campari',
    cultura: 'O tiki que a coquetelaria moderna resgatou do esquecimento',
  },
  'bees-knees': {
    origem: 'Anos 1920, durante a Lei Seca americana',
    criador: 'Atribuído a Frank Meier, do Ritz de Paris',
    historia: 'A explicação tradicional é que o mel e o limão serviam para disfarçar o gosto do gin clandestino, feito às pressas em banheira. Historiadores contestam: gin de contrabando de qualidade existia, e o drink funciona bem demais para ser só disfarce. O nome é gíria dos anos 1920 — <i>the bee\'s knees</i> queria dizer "o melhor que existe".',
    curiosidade: 'Mel puro não se dissolve em bebida gelada: ele afunda e vira uma bola no fundo do copo. Por isso se faz xarope de mel com água morna antes de bater.',
    ocasiao: 'Aperitivo, tarde',
    temperatura: 'Bem gelado, taça sem gelo',
    harmoniza: 'Queijos, torradas com mel, castanhas',
    variacoes: 'Gold Rush (com bourbon), Air Mail (com espumante)',
    cultura: 'Gíria dos anos 1920 que virou coquetel',
  },
  'gold-rush': {
    origem: 'Nova York, Estados Unidos · por volta de 2001',
    criador: 'T.J. Siegal, no Milk & Honey',
    historia: 'Siegal era cliente e amigo de Sasha Petraske, dono do Milk & Honey — o bar que reinventou a coquetelaria clássica em Nova York. A ideia foi simples ao ponto de parecer óbvia depois: pegar o Whiskey Sour e trocar o açúcar por mel. Virou um dos poucos drinks recentes a entrar no cânone.',
    curiosidade: 'É a prova de que criar um clássico moderno não exige ingrediente exótico: três coisas, uma troca, e o resultado atravessou vinte anos.',
    ocasiao: 'Noite, conversa longa, inverno',
    temperatura: 'Gelado, pedra grande',
    harmoniza: 'Queijo curado, castanhas, chocolate',
    variacoes: "Bee's Knees (com gin), Penicillin (com gengibre e turfa)",
    cultura: 'Um dos raros clássicos nascidos no século XXI',
  },
  'appletini': {
    origem: 'Los Angeles, Estados Unidos · 1996',
    criador: 'Adam Karsten, no bar Lola\'s',
    historia: 'Nasceu no auge da moda dos "martínis" de sabor, quando qualquer coisa servida numa taça de martíni ganhava o sufixo. Dominou os anos 1990 e 2000 e depois virou piada de bar — em boa parte por culpa das versões feitas só com xarope, sem cítrico nenhum, doces ao ponto de enjoar.',
    curiosidade: 'Com limão fresco na medida certa ele deixa de ser doce demais e vira um drink honesto. O problema nunca foi a maçã: foi a falta de acidez.',
    ocasiao: 'Festa, começo de noite',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Petiscos leves, queijos frescos',
    variacoes: 'Com maçã fresca, com espumante por cima',
    cultura: 'A bebida do personagem J.D. na série <i>Scrubs</i>',
  },
  'mule-de-gengibre': {
    origem: 'Variação caseira do Moscow Mule',
    criador: 'Popular, de bar',
    historia: 'O Moscow Mule nasceu em Los Angeles, em 1941, de um encontro entre três pessoas com estoque parado: vodka que ninguém comprava, ginger beer que não vendia e um lote de canecas de cobre. Onde não há ginger beer, o xarope de gengibre com água com gás faz o mesmo trabalho — e com controle melhor da intensidade.',
    curiosidade: 'A caneca de cobre não é folclore: o metal conduz o frio rápido e a bebida chega à boca mais gelada do que num copo de vidro.',
    ocasiao: 'Calor, encontro informal',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Comida apimentada, frituras, comida asiática',
    variacoes: 'Moscow Mule (com ginger beer), com gin (Gin-Gin Mule)',
    cultura: 'O drink que vendeu vodka para os Estados Unidos',
  },
  'spritz-de-tangerina': {
    origem: 'Vêneto, Itália · tradição adaptada',
    criador: 'Popular, de bar',
    historia: 'O spritz descende da ocupação austríaca do norte da Itália, no século XIX: os soldados achavam o vinho local forte demais e pediam que fosse cortado com água — <i>spritzen</i>, borrifar, em alemão. A fórmula sobreviveu à ocupação e virou o aperitivo de toda a região; a tangerina é uma das muitas frutas que entraram no lugar do amaro.',
    curiosidade: 'Mexer demais mata o spritz. O gás é ingrediente, não enfeite: uma volta de colher, de baixo para cima, e para.',
    ocasiao: 'Aperitivo, tarde ao ar livre',
    temperatura: 'Muito gelado, taça cheia de gelo',
    harmoniza: 'Azeitonas, queijos frescos, aperitivos',
    variacoes: 'Aperol Spritz, Hugo Spritz, com maracujá',
    cultura: 'Herança de uma ocupação militar que virou hora do aperitivo',
  },
  'tangerina-tonica': {
    origem: 'Coquetelaria contemporânea de gin-tônica',
    criador: 'Popular, de bar',
    historia: 'A gin-tônica autoral, com taça de balão e guarnições pensadas uma a uma, nasceu no País Basco e se espalhou pela Espanha nos anos 2000, chegando ao Brasil na década seguinte. A tangerina entrou nessa leva — é doce o bastante para domar o quinino sem apagar o zimbro do gin.',
    curiosidade: 'A taça grande não é pose: a boca larga concentra o aroma do gin logo abaixo do nariz, e o gelo em excesso derrete mais devagar do que pouco gelo.',
    ocasiao: 'Aperitivo, noite de calor',
    temperatura: 'Muito gelada, taça cheia de gelo',
    harmoniza: 'Petiscos, queijos, frutos do mar',
    variacoes: 'Com alecrim, com zimbro, com pimenta rosa',
    cultura: 'A gin-tônica espanhola que redesenhou o drink mais simples do mundo',
  },
  'limonada-de-gengibre': {
    origem: 'Preparo caseiro, sem data',
    criador: 'Popular, sem autoria',
    historia: 'Gengibre com limão é dupla antiga em cozinha e farmácia caseira muito antes de virar bebida de bar. O xarope apenas resolve o problema prático: gengibre fresco é difícil de dosar, e a raiz varia muito de força de um pedaço para outro.',
    curiosidade: 'O ardido do gengibre vem do gingerol, o mesmo composto que dá o calor. Ele é solúvel em álcool e em açúcar — por isso o xarope entrega mais ardência do que a raiz batida na água.',
    ocasiao: 'Qualquer hora, calor, para quem não bebe',
    temperatura: 'Muito gelada, copo cheio de gelo',
    harmoniza: 'Comida apimentada, comida asiática, frituras',
    variacoes: 'Com hortelã, com limão siciliano, com pepino',
    cultura: 'Remédio de avó que virou drink de cardápio',
  },
  'maca-verde-refresco': {
    origem: 'Preparo caseiro contemporâneo',
    criador: 'Popular, sem autoria',
    historia: 'É o Appletini sem a vodka — e, sem o álcool para segurar, o limão passa a ser obrigatório. Ganhou espaço nos cardápios junto com a leva de bebidas sem álcool que os bares passaram a levar a sério a partir dos anos 2010.',
    curiosidade: 'O verde do xarope não vem da maçã: maçã verde espremida dá um suco pardo, que oxida em minutos. A cor é acrescentada — e é ela que faz o cérebro sentir mais acidez do que a bebida realmente tem.',
    ocasiao: 'Tarde, calor, para quem não bebe',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Petiscos leves, saladas, queijos frescos',
    variacoes: 'Com hortelã, com espumante (vira coquetel), com pepino',
    cultura: 'Filho sem álcool do coquetel mais dos anos 1990 que existe',
  },
  'daiquiri-morango': {
    origem: 'Cuba · variação do Daiquiri clássico',
    criador: 'Popular; a versão frozen é atribuída ao Floridita de Havana',
    historia: 'O Floridita de Havana passou a bater daiquiris no gelo nos anos 1930, e a fruta entrou junto. A versão de morango atravessou o século e ficou tão associada a máquina de resort que quase se esqueceu que, batida na coqueteleira, ela é um drink de bar bem seco.',
    curiosidade: 'Morango tem pouquíssima acidez própria. Sem o limão, o drink fica chapado e enjoativo — é o cítrico que faz a fruta parecer mais fruta.',
    ocasiao: 'Calor, tarde, começo de noite',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Sobremesas leves, queijos frescos, frutas',
    variacoes: 'Frozen, com framboesa, com manjericão',
    cultura: 'O drink de piscina que já foi coquetel sério — e volta a ser',
  },
  'floradora': {
    origem: 'Nova York, Estados Unidos · por volta de 1900',
    criador: 'Batizado a partir de um musical da Broadway',
    historia: '<i>Florodora</i> foi um sucesso estrondoso da Broadway em 1900, célebre pelas seis coristas conhecidas como <i>Florodora Girls</i>. O drink pegou o nome — com a grafia trocada pelo caminho — e virou moda nos hotéis de Nova York antes da Lei Seca.',
    curiosidade: 'É praticamente um Gin Fizz com framboesa e gengibre no lugar da água com gás. Sumiu por quase um século e voltou junto com a moda das ginger beers artesanais.',
    ocasiao: 'Tarde, aperitivo, calor',
    temperatura: 'Gelado, copo cheio de gelo',
    harmoniza: 'Petiscos leves, queijos frescos, frutas vermelhas',
    variacoes: 'Com framboesa fresca, com ginger ale, com espumante',
    cultura: 'Um musical da Broadway de 1900 que sobreviveu como bebida',
  },
  'pornstar-martini': {
    origem: 'Londres, Inglaterra · 2002',
    criador: 'Douglas Ankrah, no Townhouse',
    historia: 'Ankrah criou o drink pensando num bar que conhecera na Cidade do Cabo e o batizou primeiro de Maverick Martini. O nome atual pegou depois, e ele mesmo dizia que a ideia era um drink que se bebesse "com prazer e sem cerimônia". Virou um dos coquetéis mais pedidos do Reino Unido.',
    curiosidade: 'O espumante servido à parte não é firula: alterna-se um gole doce e um gole seco, e é esse contraste — não a mistura — que faz o drink funcionar.',
    ocasiao: 'Noite, comemoração, festa',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Sobremesas, frutas tropicais',
    variacoes: 'Com maracujá fresco, sem álcool, com gin',
    cultura: 'Um dos drinks mais vendidos dos bares britânicos',
  },
  'hot-toddy': {
    origem: 'Escócia / Irlanda · século XVIII',
    criador: 'Popular, sem autoria',
    historia: 'Nasceu como remédio caseiro de inverno, e não como coquetel: uísque, mel, limão e água quente para atravessar noites frias e resfriados. A palavra <i>toddy</i> vem do hindi <i>tārī</i>, a seiva fermentada de palmeira, trazida pelos britânicos da Índia.',
    curiosidade: 'O calor é o ingrediente mais delicado: acima de uns 80 °C o álcool começa a evaporar e leva os aromas junto. Água fervendo estraga o drink.',
    ocasiao: 'Noite fria, resfriado, fim de noite',
    temperatura: 'Quente, nunca fervendo',
    harmoniza: 'Biscoitos, castanhas, bolo de especiarias',
    variacoes: 'Com rum, com conhaque, com chá no lugar da água',
    cultura: 'Receita de avó que nunca saiu do cardápio de inverno',
  },
  'espresso-tonica': {
    origem: 'Escandinávia · anos 2010',
    criador: 'Cafeterias de terceira onda, autoria disputada',
    historia: 'Apareceu em cafeterias suecas e norueguesas no começo dos anos 2010 e se espalhou pelo mundo pelo circuito do café especial. É um drink de cafeteria antes de ser de bar: nasceu para mostrar as notas cítricas e florais de cafés claros, que se perdem no leite.',
    curiosidade: 'O café flutua sobre a tônica porque a tônica, cheia de açúcar, é mais densa. A camada dura alguns minutos e é a razão de o café entrar por último.',
    ocasiao: 'Tarde, calor, para quem não bebe',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Doces cítricos, biscoitos amanteigados',
    variacoes: 'Com laranja, sem xarope, com água com gás',
    cultura: 'Nascido na terceira onda do café, não na coquetelaria',
  },
  'mint-julep': {
    origem: 'Sul dos Estados Unidos · registrado em 1803',
    criador: 'Popular, sem autoria',
    historia: 'Começou como remédio matinal do interior americano — destilado com açúcar e ervas para "assentar o estômago" ao amanhecer. Virou o drink oficial do Kentucky Derby em 1938, e até hoje se servem mais de cem mil deles nos dois dias da corrida.',
    curiosidade: 'O copo tradicional é de metal e se segura pela base, nunca pelo corpo: a mão esquenta o metal e derrete a camada de geada que se forma por fora — que é o ponto do drink.',
    ocasiao: 'Tarde de calor, corrida de cavalo, varanda',
    temperatura: 'Gelado, gelo triturado até formar geada',
    harmoniza: 'Comida do sul dos Estados Unidos, defumados, castanhas',
    variacoes: 'Com conhaque (o original), com pêssego, com rum',
    cultura: 'Drink oficial do Kentucky Derby desde 1938',
  },
  'corn-n-oil': {
    origem: 'Barbados · tradicional',
    criador: 'Popular, sem autoria',
    historia: 'É o drink nacional não oficial de Barbados, ilha onde tanto o rum quanto o falernum foram inventados. O falernum — xarope de especiarias, cravo, gengibre e limão — é a assinatura da coquetelaria de Barbados desde o século XIX.',
    curiosidade: 'O nome vem da aparência: as gotas de angostura escorrendo sobre o rum escuro lembram óleo derramado. Há quem diga que "corn" seria corruptela de <i>Kill-Devil</i>, o apelido antigo do rum — mas é hipótese, não fato.',
    ocasiao: 'Fim de noite, digestivo',
    temperatura: 'Gelado, pedra grande',
    harmoniza: 'Comida caribenha, chocolate amargo, especiarias',
    variacoes: 'Com mais angostura, com rum da Jamaica, sem limão',
    cultura: 'A cara líquida de Barbados, onde o rum foi inventado',
  },
  'tommys-margarita': {
    origem: 'São Francisco, Estados Unidos · anos 1990',
    criador: 'Julio Bermejo, no Tommy\'s Mexican Restaurant',
    historia: 'Bermejo trocou o licor de laranja por xarope de agave — o mesmo agave de que a tequila é feita — e o resultado foi tão convincente que virou padrão entre bartenders. É um dos poucos drinks modernos aceitos como clássico enquanto o criador ainda trabalhava atrás do balcão.',
    curiosidade: 'Sem o licor de laranja, não há nada para mascarar a tequila. É por isso que a receita exige tequila 100% agave: com destilado ruim, o drink denuncia na hora.',
    ocasiao: 'Aperitivo, comida mexicana, noite',
    temperatura: 'Bem gelada, gelo novo',
    harmoniza: 'Tacos, ceviche, comida apimentada, guacamole',
    variacoes: 'Com mezcal, picante, com toranja',
    cultura: 'A Margarita que os bartenders pedem quando não estão trabalhando',
  },
  'paper-plane': {
    origem: 'Nova York, Estados Unidos · 2007',
    criador: 'Sam Ross, criado para o Violet Hour, de Chicago',
    historia: 'Ross trabalhava no Milk & Honey quando o Violet Hour lhe pediu um drink para a carta de abertura. Ele partiu do Last Word — quatro partes iguais — e trocou todos os ingredientes. O nome vem da música <i>Paper Planes</i>, de M.I.A., que tocava sem parar naquele ano.',
    curiosidade: 'A simetria não é enfeite: quatro coisas em quantidade idêntica é uma estrutura, e é ela que permite trocar os ingredientes inteiros sem perder o equilíbrio. Foi assim que nasceram o Naked & Famous e vários outros.',
    ocasiao: 'Aperitivo, começo de noite',
    temperatura: 'Bem gelado, taça sem gelo',
    harmoniza: 'Embutidos, queijo curado, azeitonas',
    variacoes: 'Naked & Famous (mezcal), com rye no lugar do bourbon',
    cultura: 'Batizado por uma música de M.I.A. de 2007',
  },
  'naked-and-famous': {
    origem: 'Nova York, Estados Unidos · 2011',
    criador: 'Joaquín Simó, no Death & Co',
    historia: 'Simó pegou a estrutura do Paper Plane e a levou para o mezcal. O nome saiu de uma conversa de balcão sobre a banda The Naked and Famous — sem nenhuma razão mais profunda, como ele mesmo fez questão de dizer depois.',
    curiosidade: 'É um caso raro e documentado de linhagem: Last Word (1920) → Paper Plane (2007) → Naked & Famous (2011). Três drinks, três décadas, a mesma arquitetura de quatro partes iguais.',
    ocasiao: 'Aperitivo, noite',
    temperatura: 'Bem gelado, taça sem gelo',
    harmoniza: 'Comida mexicana, queijos fortes, defumados',
    variacoes: 'Com tequila, com Campari no lugar do Aperol',
    cultura: 'Terceira geração de uma família de drinks de partes iguais',
  },
  'last-word': {
    origem: 'Detroit, Estados Unidos · por volta de 1920',
    criador: 'Detroit Athletic Club; revivido por Murray Stenson em 2004',
    historia: 'Apareceu num livro de 1951 e desapareceu em seguida. Em 2004, o bartender Murray Stenson o encontrou nesse livro velho e o colocou na carta do Zig Zag Café, em Seattle. Espalhou-se pelo país inteiro e virou o símbolo do movimento de resgate da coquetelaria clássica.',
    curiosidade: 'É o avô de toda a família de partes iguais. Depois dele vieram Paper Plane, Naked & Famous, Division Bell e uma dúzia de outros construídos sobre a mesma régua.',
    ocasiao: 'Aperitivo, noite',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Queijos, azeitonas, comida herbácea',
    variacoes: 'Division Bell (mezcal), Final Ward (rye), com Chartreuse amarelo',
    cultura: 'O drink que um bartender de Seattle tirou do esquecimento em 2004',
  },
  'division-bell': {
    origem: 'Nova York, Estados Unidos · 2011',
    criador: 'Phil Ward, no Mayahuel',
    historia: 'Ward abriu o Mayahuel dedicado exclusivamente a tequila e mezcal, e passou a reescrever clássicos com agave. O Division Bell é o Last Word nessa chave. O nome vem do álbum do Pink Floyd.',
    curiosidade: 'Ward é o mesmo bartender do Oaxaca Old Fashioned. Sua receita de sempre era pegar um clássico consagrado e trocar o destilado por agave — e funcionou tantas vezes que virou escola.',
    ocasiao: 'Noite, aperitivo',
    temperatura: 'Bem gelado, taça sem gelo',
    harmoniza: 'Comida mexicana, frutos do mar, pimenta',
    variacoes: 'Com tequila, com Campari, com toranja',
    cultura: 'Nomeado a partir do álbum <i>The Division Bell</i>, do Pink Floyd',
  },
  'oaxaca-old-fashioned': {
    origem: 'Nova York, Estados Unidos · 2007',
    criador: 'Phil Ward, no Death & Co',
    historia: 'Ward aplicou ao Old Fashioned a ideia que definiria sua carreira: manter a estrutura e trocar o destilado. Tequila como corpo, um fio de mezcal para dar fumaça, agave no lugar do açúcar. É hoje um dos drinks de agave mais pedidos do mundo.',
    curiosidade: 'A proporção de mezcal é pequena de propósito — 15 ml em 60. Ele não é um dos destilados do drink: é tempero, e em dose cheia atropela a tequila.',
    ocasiao: 'Noite, digestivo, conversa longa',
    temperatura: 'Gelado, pedra grande',
    harmoniza: 'Carnes grelhadas, chocolate amargo, mole',
    variacoes: 'Só com mezcal, com bitters de chocolate',
    cultura: 'O drink que provou que agave também envelhece bem em copo baixo',
  },
  'gin-basil-smash': {
    origem: 'Hamburgo, Alemanha · 2008',
    criador: 'Jörg Meyer, no Le Lion',
    historia: 'Meyer publicou a receita no blog do próprio bar e ela se espalhou pela Europa em questão de meses — um dos primeiros drinks a viralizar pela internet, antes de isso ser comum. Ele o chamava de "Gin Pesto" no começo.',
    curiosidade: 'Ao contrário da hortelã, que se machuca de leve, o manjericão precisa ser socado com força. A folha é mais grossa e o óleo não sai sem pressão.',
    ocasiao: 'Tarde, aperitivo, calor',
    temperatura: 'Gelado, gelo novo',
    harmoniza: 'Comida italiana, tomate, queijos frescos, peixe',
    variacoes: 'Com hortelã, com pepino, com gim envelhecido',
    cultura: 'Um dos primeiros coquetéis a viralizar por um blog',
  },
  'old-cuban': {
    origem: 'Nova York, Estados Unidos · 2001',
    criador: 'Audrey Saunders, no Pegu Club',
    historia: 'Saunders descreveu o drink como um cruzamento entre o Mojito e o French 75 — rum e hortelã de um lado, espumante do outro, com angostura para dar espinha. O Pegu Club foi um dos bares que definiram a coquetelaria moderna, e Saunders formou boa parte da geração seguinte.',
    curiosidade: 'A angostura num drink com espumante é o detalhe que o separa de um Mojito borbulhante: são as gotas amargas que impedem o conjunto de ficar meramente doce e festivo.',
    ocasiao: 'Comemoração, noite, aperitivo',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Frutos do mar, canapés, comida leve',
    variacoes: 'Com rum branco, com champanhe, com hortelã em excesso',
    cultura: 'Nascido no Pegu Club, o bar que formou a geração atual',
  },
  'trinidad-sour': {
    origem: 'Nova York, Estados Unidos · 2009',
    criador: 'Giuseppe González',
    historia: 'González inverteu a regra mais básica da coquetelaria: bitters entram em gotas. Aqui a angostura é a base, em dose cheia, e o uísque é que aparece em quantidade de tempero. Quase ninguém acreditou que funcionaria — e funciona.',
    curiosidade: 'Uma dose de angostura tem cerca de 44% de álcool, mais que muitos destilados. O drink não é fraco por ser feito de bitters: é forte e amargo em partes iguais.',
    ocasiao: 'Digestivo, fim de noite, para quem já provou de tudo',
    temperatura: 'Bem gelado, taça sem gelo',
    harmoniza: 'Chocolate amargo, castanhas, especiarias',
    variacoes: 'Com rye, com orgeat caseiro, com limão siciliano',
    cultura: 'O drink que transformou o tempero em ingrediente principal',
  },
  'siesta': {
    origem: 'Nova York, Estados Unidos · 2006',
    criador: 'Katie Stipe, no Flatiron Lounge',
    historia: 'Stipe pegou o Hemingway Daiquiri e o levou para a tequila, acrescentando Campari. O resultado ficou entre o sour e o aperitivo italiano, e entrou nas cartas de bar do mundo inteiro em poucos anos.',
    curiosidade: 'Toranja e Campari são amargos de naturezas diferentes — um é frutado, o outro é herbáceo. Juntos, cada um cobre o buraco que o outro deixa.',
    ocasiao: 'Aperitivo, tarde de calor',
    temperatura: 'Bem gelada, taça sem gelo',
    harmoniza: 'Ceviche, tacos, azeitonas, comida apimentada',
    variacoes: 'Com mezcal, com Aperol, servido com gelo',
    cultura: 'A ponte entre o sour americano e o aperitivo italiano',
  },
  'eastside': {
    origem: 'Nova York, Estados Unidos · anos 2000',
    criador: 'Autoria disputada entre bares nova-iorquinos',
    historia: 'Descende do Southside, drink de gim com hortelã dos anos 1920 que a lenda associa à máfia de Chicago — sem nenhuma prova. O Eastside acrescenta pepino, e apareceu em vários bares de Nova York quase ao mesmo tempo, o que torna a autoria impossível de fixar.',
    curiosidade: 'Pepino não tem sabor forte: tem água e frescor. Ele não compete com a hortelã, apenas dilui a intensidade dela — que é exatamente o problema do Southside.',
    ocasiao: 'Tarde de calor, aperitivo, ao ar livre',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Saladas, peixe, comida leve, queijos frescos',
    variacoes: 'Southside (sem pepino), com vodka, com manjericão',
    cultura: 'O Southside dos anos 1920 com pepino e oitenta anos a mais',
  },
  'pisco-sour': {
    origem: 'Lima, Peru · anos 1920',
    criador: 'Victor Vaughen Morris, no Morris Bar',
    historia: 'Morris era um americano que abriu um bar em Lima e adaptou o Whiskey Sour ao destilado local. A clara de ovo e as gotas de angostura vieram depois, provavelmente pelas mãos de seu funcionário Mario Bruiget. Peru e Chile disputam a paternidade do pisco até hoje — e, por tabela, a do drink.',
    curiosidade: 'O Peru tem um feriado oficial para ele: o Dia do Pisco Sour, no primeiro sábado de fevereiro, instituído por decreto em 2003.',
    ocasiao: 'Aperitivo, almoço longo, comemoração',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Ceviche, frutos do mar, batata, milho',
    variacoes: 'De maracujá, de coca, chileno (sem clara nem angostura)',
    cultura: 'Tem feriado nacional próprio no Peru desde 2003',
  },
  'sazerac': {
    origem: 'Nova Orleans, Estados Unidos · meados do século XIX',
    criador: 'Ligado ao Sazerac Coffee House',
    historia: 'Começou com conhaque francês da marca Sazerac-de-Forge. Quando a filoxera devastou os vinhedos da França nos anos 1870, o conhaque sumiu do mercado e o centeio americano tomou seu lugar — a troca nunca foi desfeita. É o coquetel oficial de Nova Orleans por decreto legislativo de 2008.',
    curiosidade: 'O absinto nunca fica no copo: gira-se e joga-se fora. Sobra só o filme aromático nas paredes, e é dele que vem o anis que se sente antes do primeiro gole.',
    ocasiao: 'Noite, digestivo, conversa séria',
    temperatura: 'Gelado, servido sem gelo',
    harmoniza: 'Comida cajun, carnes, chocolate amargo',
    variacoes: 'Com conhaque (o original), com Peychaud\'s, com rye',
    cultura: 'Coquetel oficial de Nova Orleans por lei estadual',
  },
  'corpse-reviver': {
    origem: 'Londres, Inglaterra · registrado em 1930',
    criador: 'Harry Craddock, no Savoy Cocktail Book',
    historia: 'Os <i>corpse revivers</i> eram uma categoria inteira de drinks do século XIX, tomados de manhã para ressuscitar quem tinha exagerado na véspera. Craddock catalogou o número 2 em 1930 com um aviso que virou célebre: "quatro destes, tomados em sequência rápida, revivem o cadáver de novo".',
    curiosidade: 'O original leva Kina Lillet, um aperitivo de quinino que saiu de linha em 1986. Toda receita moderna é, por definição, uma aproximação — o vermute seco é a substituição mais comum.',
    ocasiao: 'Brunch, aperitivo, ressaca',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Ovos, salmão defumado, comida de brunch',
    variacoes: 'Corpse Reviver nº 1 (conhaque), com Cocchi Americano',
    cultura: 'Vem com aviso de dose escrito pelo próprio autor, em 1930',
  },
  'aviation': {
    origem: 'Nova York, Estados Unidos · 1916',
    criador: 'Hugo Ensslin, no Hotel Wallick',
    historia: 'Ensslin publicou a receita original em 1916, com licor de violeta — que dava ao drink o tom azulado de céu que explica o nome. Quando Craddock o reimprimiu em Londres, em 1930, cortou a violeta, que havia sumido do mercado. Por décadas o Aviation foi bebido sem a cor que lhe deu nome.',
    curiosidade: 'O maraschino não é doce como parece: é seco, feito da fruta inteira com caroço, e é o caroço que traz o amargo de amêndoa. Passar de 15 ml transforma o drink em xarope.',
    ocasiao: 'Aperitivo, começo de noite',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Frutos do mar, canapés, queijos frescos',
    variacoes: 'Com licor de violeta (o original), Blue Moon, Moonlight',
    cultura: 'Um drink que passou décadas sem a cor que lhe deu nome',
  },
  'hemingway-daiquiri': {
    origem: 'Havana, Cuba · anos 1930',
    criador: 'Constantino Ribalaigua Vert, no Floridita',
    historia: 'Hemingway era diabético e detestava bebida doce. Pediu ao barman do Floridita um daiquiri sem açúcar nenhum e com o dobro de rum. Constantino acrescentou toranja e maraschino para dar corpo ao que sobrou. A versão dupla ficou conhecida como Papa Doble.',
    curiosidade: 'Sem açúcar, o drink depende inteiramente da qualidade do rum e da toranja. É o daiquiri mais difícil de fazer bem justamente por não ter onde esconder nada.',
    ocasiao: 'Calor, aperitivo, tarde',
    temperatura: 'Muito gelado, taça sem gelo',
    harmoniza: 'Ceviche, ostras, peixe cru, frutos do mar',
    variacoes: 'Papa Doble (dose dupla, sem açúcar), frozen',
    cultura: 'O pedido de Hemingway no Floridita, anotado pelo barman',
  },
  'vodka-ice': {
    origem: 'Versão de bar do refrigerante alcoólico',
    criador: 'Popular; a categoria nasceu comercialmente nos anos 1990',
    historia: 'Os <i>alcopops</i> — refrigerantes alcoólicos de garrafa — apareceram na Austrália e no Reino Unido no começo dos anos 1990 e viraram fenômeno mundial. A fórmula é simples e antiga: destilado neutro, cítrico, açúcar e gás. Feita na hora, com limão espremido, é a mesma bebida sem o gosto de conservante.',
    curiosidade: 'A garrafa industrial costuma ter entre 4% e 5% de álcool, menos que muitos vinhos. O que engana é o açúcar: ele esconde o álcool e faz o segundo copo parecer tão leve quanto o primeiro.',
    ocasiao: 'Calor, festa, encontro informal',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Petiscos, frituras, comida de festa',
    variacoes: 'Com frutas vermelhas, com maracujá, com tangerina',
    cultura: 'A versão caseira de uma categoria inteira de garrafa',
  },
  'screwdriver': {
    origem: 'Oriente Médio · anos 1940',
    criador: 'Popular, sem autoria',
    historia: 'A explicação mais repetida é que operários americanos em campos de petróleo do Golfo Pérsico misturavam vodka ao suco de laranja e mexiam com a única coisa à mão: uma chave de fenda. A história é boa demais para ser verificável, mas o nome apareceu impresso pela primeira vez em 1949 e nunca teve outra explicação.',
    curiosidade: 'É o drink que mais denuncia suco ruim. Com dois ingredientes e nenhuma técnica, o suco de caixinha aparece inteiro — laranja espremida na hora faz outro drink.',
    ocasiao: 'Brunch, tarde, encontro informal',
    temperatura: 'Gelado, copo cheio de gelo',
    harmoniza: 'Comida de brunch, ovos, petiscos leves',
    variacoes: 'Harvey Wallbanger (com Galliano), com toranja, com espumante',
    cultura: 'Batizado, dizem, pela ferramenta que servia de colher',
  },
  'cape-codder': {
    origem: 'Estados Unidos · 1945',
    criador: 'Criado pela cooperativa Ocean Spray',
    historia: 'Não nasceu num bar: nasceu no marketing. A Ocean Spray, cooperativa de produtores de cranberry de Massachusetts, criou o drink em 1945 para vender suco fora da época do Dia de Ação de Graças. Chamava-se Red Devil no começo; virou Cape Codder nos anos 1960, pelo nome da península.',
    curiosidade: 'Cranberry puro é intragável de tão ácido e amargo — o suco vendido é sempre adoçado. É por isso que a rodela de limão espremida no fim faz tanta diferença: ela devolve a acidez que o açúcar tirou.',
    ocasiao: 'Encontro informal, tarde, festa',
    temperatura: 'Gelado, copo cheio de gelo',
    harmoniza: 'Petiscos, queijos, frutos do mar',
    variacoes: 'Sea Breeze (com toranja), Bay Breeze (com abacaxi), Madras (com laranja)',
    cultura: 'Um coquetel inventado por uma cooperativa agrícola para vender suco',
  },
  'sea-breeze': {
    origem: 'Estados Unidos · anos 1930, na forma atual desde os anos 1980',
    criador: 'Popular; a versão com cranberry vem da Ocean Spray',
    historia: 'O nome existe desde os anos 1930, quando designava um drink com gin e granadina — nada a ver com o atual. A versão que se bebe hoje é dos anos 1980 e faz parte da mesma família que a Ocean Spray criou para escoar cranberry.',
    curiosidade: 'As duas camadas não são truque de bar: o suco de cranberry é mais denso que o de toranja e afunda sozinho. Mexer demais apaga o efeito.',
    ocasiao: 'Tarde de calor, praia, piscina',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Frutos do mar, saladas, comida leve',
    variacoes: 'Bay Breeze (abacaxi), Cape Codder (só cranberry)',
    cultura: 'Trilha sonora dos anos 1980 em forma de copo',
  },
  'bay-breeze': {
    origem: 'Estados Unidos · anos 1980',
    criador: 'Popular, sem autoria',
    historia: 'É o Sea Breeze com abacaxi no lugar da toranja, e a troca muda o público: sai o amargo cítrico, entra o doce tropical. Também é conhecido como Hawaiian Sea Breeze.',
    curiosidade: 'Abacaxi e cranberry funcionam juntos por motivos opostos — um traz açúcar e enzimas, o outro traz taninos. É o tanino que impede a doçura de virar enjoo.',
    ocasiao: 'Piscina, festa, tarde de calor',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Comida tropical, frutas, petiscos',
    variacoes: 'Sea Breeze (toranja), com rum, com licor de coco',
    cultura: 'O irmão doce do Sea Breeze',
  },
  'woo-woo': {
    origem: 'Estados Unidos · anos 1980',
    criador: 'Popular, sem autoria',
    historia: 'Nasceu no auge dos drinks de licor de pêssego, quando o schnapps era o ingrediente mais vendido dos bares americanos. É primo direto do Sex on the Beach — mesma família, mesma década, menos ingredientes.',
    curiosidade: 'Licor de pêssego tem em geral entre 15% e 20% de álcool, menos da metade de um destilado. É por isso que a família inteira é leve mesmo parecendo forte de tão doce.',
    ocasiao: 'Festa, encontro informal',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Petiscos, comida de festa, frutas',
    variacoes: 'Sex on the Beach (com laranja), com vodka de frutas',
    cultura: 'Retrato dos anos 1980, com licor de pêssego e tudo',
  },
  'fuzzy-navel': {
    origem: 'Estados Unidos · 1984',
    criador: 'Atribuído a Ray Foley, editor do Bartender Magazine',
    historia: 'Foley criou o drink para ajudar a lançar o schnapps de pêssego no mercado americano. O nome é um trocadilho: <i>fuzzy</i> pela pele do pêssego e <i>navel</i> pela laranja-de-umbigo. Foi um dos drinks mais vendidos da década.',
    curiosidade: 'É provavelmente o coquetel mais fácil que existe: dois ingredientes, nenhuma técnica, nenhum equipamento. E é um bom primeiro drink para quem está começando a experimentar.',
    ocasiao: 'Tarde, brunch, para quem está começando',
    temperatura: 'Gelado, copo cheio de gelo',
    harmoniza: 'Frutas, sobremesas leves, brunch',
    variacoes: 'Hairy Navel (com vodka), com espumante, com manga',
    cultura: 'Criado para vender schnapps — e vendeu muito',
  },
  'malibu-abacaxi': {
    origem: 'Caribe · o licor é de 1980',
    criador: 'Popular; o Malibu nasceu em Barbados',
    historia: 'O licor de coco foi criado em 1980, em Barbados, justamente para simplificar a Piña Colada — que exigia creme de coco, liquidificador e paciência. Com o licor pronto, bastava juntar abacaxi. A bebida que ele veio simplificar acabou ofuscada pela versão simples.',
    curiosidade: 'Tem cerca de 21% de álcool, bem menos que o rum de que deriva. Por isso a dose costuma ser maior — e o drink continua leve.',
    ocasiao: 'Praia, piscina, verão',
    temperatura: 'Muito gelado, copo cheio de gelo',
    harmoniza: 'Frutas tropicais, comida caribenha, grelhados',
    variacoes: 'Piña Colada, com cranberry (Malibu Bay Breeze), com maracujá',
    cultura: 'Um licor inventado para encurtar caminho até a Piña Colada',
  },
  'vodka-melancia': {
    origem: 'Preparo de verão, sem data',
    criador: 'Popular, sem autoria',
    historia: 'Melancia com destilado é combinação de quintal antes de ser de bar — a fruta é doce, aguada e barata no verão, e aceita bem qualquer coisa neutra. Entrou nas cartas junto com a onda de drinks de fruta fresca dos anos 2010.',
    curiosidade: 'Melancia é cerca de 92% água. Ela não dilui o drink por acidente: ela é a diluição, e por isso leva menos gelo e menos mixer que qualquer outra fruta.',
    ocasiao: 'Verão, piscina, tarde de calor',
    temperatura: 'Muito gelada, copo cheio de gelo',
    harmoniza: 'Queijo branco, salada, churrasco',
    variacoes: 'Com hortelã, com tequila, com pimenta rosa',
    cultura: 'Drink de quintal que virou cardápio de verão',
  },
  'coco-limao': {
    origem: 'Litoral brasileiro · preparo tradicional',
    criador: 'Popular, sem autoria',
    historia: 'Água de coco com limão é bebida de praia brasileira muito antes de qualquer bar a servir em copo alto. É também isotônico natural: repõe potássio e sódio, o que explica por que ela funciona tão bem no calor.',
    curiosidade: 'A água de coco já traz sal e açúcar próprios em proporções parecidas com as de um isotônico industrial. O limão não adoça nem salga nada — só acorda os dois que já estão lá.',
    ocasiao: 'Praia, calor, depois de treinar, para quem não bebe',
    temperatura: 'Muito gelada, copo cheio de gelo',
    harmoniza: 'Comida de praia, petiscos, frutos do mar',
    variacoes: 'Com abacaxi, com gengibre, com maracujá',
    cultura: 'Isotônico natural que o litoral brasileiro bebe há gerações',
  },
};

// ---------- Ficha derivada: vale para as 47 receitas ----------
function nivelDaReceita(r) {
  const p = (r.preparo || '').toLowerCase();
  const temClara = r.ing.some(i => i.id === 'ovo');
  if (temClara || p.includes('liquidificador') || p.includes('coe duplo')) return 3;
  if (p.includes('bata') || p.includes('macere') || p.includes('coqueteleira')) return 2;
  return 1;
}

const NIVEL_NOMES = { 1: 'iniciante', 2: 'intermediário', 3: 'avançado' };

function tempoDaReceita(r) {
  const n = nivelDaReceita(r);
  const ings = r.ing.filter(i => !BASICOS.has(i.id)).length;
  return Math.min(6, n + Math.ceil(ings / 3));
}

// ---------- Trilha: o que tocar enquanto se bebe ----------
// A origem manda mais que o sabor — um samba não combina com um Manhattan, e
// jazz de bar não combina com uma caipifruta. Onde não há país, o perfil decide.
const TRILHA_POR_PAIS = {
  'Brasil': { busca: 'samba e bossa nova', nome: 'samba e bossa' },
  'Cuba': { busca: 'son cubano buena vista', nome: 'son cubano' },
  'México': { busca: 'cumbia mexicana', nome: 'cumbia' },
  'Itália': { busca: 'italian lounge dolce vita', nome: 'lounge italiano' },
  'França': { busca: 'chanson française jazz manouche', nome: 'chanson e jazz manouche' },
  'Espanha': { busca: 'flamenco rumba catalana', nome: 'rumba' },
  'Irlanda': { busca: 'irish folk', nome: 'folk irlandês' },
  'Porto Rico': { busca: 'salsa boricua', nome: 'salsa' },
  'Bermudas': { busca: 'calypso caribbean', nome: 'calypso' },
  'Barbados': { busca: 'calypso caribbean', nome: 'calypso' },
  'Escócia': { busca: 'celtic folk fireside', nome: 'folk celta' },
  'Malásia': { busca: 'tropical lounge exotica', nome: 'exotica' },
  'Suécia': { busca: 'scandinavian indie folk', nome: 'indie escandinavo' },
  'Peru': { busca: 'musica criolla peruana', nome: 'música criolla' },
  'Alemanha': { busca: 'krautrock electronic berlin', nome: 'eletrônico de Berlim' },
};

// Onde o país não decide (Estados Unidos faz de tudo), o destilado decide:
// um uísque pede outra coisa que uma vodka, por mais parecidas que sejam as tags.
const TRILHA_POR_BASE = {
  'whisky': { busca: 'blues classics smoky', nome: 'blues' },
  'bourbon': { busca: 'blues classics smoky', nome: 'blues' },
  'conhaque': { busca: 'jazz standards bar', nome: 'jazz de bar' },
  'gin': { busca: 'jazz standards bar', nome: 'jazz de bar' },
};

const TRILHA_POR_TAG = [
  ['quente', 'winter jazz piano', 'jazz de inverno'],
  ['cremoso', 'soul classics slow', 'soul lento'],
  ['tropical', 'tropical beach sunset', 'verão'],
  ['sem-alcool', 'indie acustico manha', 'indie acústico'],
  ['amargo', 'jazz standards bar', 'jazz de bar'],
  ['forte', 'blues noir smoky', 'blues de fim de noite'],
  ['doce', 'r&b suave', 'R&B suave'],
  ['citrico', 'bossa nova classics', 'bossa nova'],
  ['refrescante', 'bossa nova classics', 'bossa nova'],
];

function trilhaDe(r) {
  // PAIS_DO_DRINK vem de momentos.js, que carrega depois — só é lido na renderização
  const pais = PAIS_DO_DRINK[r.id];
  if (pais && TRILHA_POR_PAIS[pais]) return TRILHA_POR_PAIS[pais];
  for (const i of r.ing) if (TRILHA_POR_BASE[i.id]) return TRILHA_POR_BASE[i.id];
  for (const [tag, busca, nome] of TRILHA_POR_TAG) {
    if (r.tags.includes(tag)) return { busca, nome };
  }
  return { busca: 'jazz standards bar', nome: 'jazz de bar' };
}

// Fica fora do bloco de história de propósito: receita própria e drink ainda
// sem verbete também merecem trilha.
function blocoTrilha(r) {
  const t = trilhaDe(r);
  return `<a class="btn btn-trilha" target="_blank" rel="noopener"
    href="https://open.spotify.com/search/${encodeURIComponent(t.busca)}">
    ♫ Ouvir ${esc(t.nome)} enquanto prepara</a>`;
}

function ocasiaoDerivada(r) {
  if (r.tags.includes('quente')) return 'Noite fria';
  if (r.tags.includes('sem-alcool')) return 'Qualquer hora do dia';
  if (r.tags.includes('cremoso')) return 'Depois do jantar';
  if (r.tags.includes('amargo')) return 'Aperitivo, antes de comer';
  if (r.tags.includes('tropical') || r.tags.includes('refrescante')) return 'Calor, tarde ao ar livre';
  return 'Noite, encontro com amigos';
}

// História guardada pelo usuário (escrita pela IA sob demanda)
function historiaDe(id) {
  return HISTORIAS[id] || Store.getHistorias()[id] || null;
}

// Bloco de história no modal. Sem história, mostra o convite — a lacuna de
// curiosidade é o que faz abrir o próximo drink.
function blocoHistoria(r, h) {
  const linha = (rotulo, valor) => valor
    ? `<li><span>${rotulo}</span><span>${valor}</span></li>` : '';

  if (!h) {
    const ficha = `<ul class="ficha-drink">
      ${linha('Ocasião', esc(ocasiaoDerivada(r)))}
      ${linha('Copo', esc(r.copo))}
    </ul>`;
    if (r.custom) return ficha;
    return `${ficha}
      <button class="btn btn-descobrir" data-descobrir="${r.id}">
        ✦ Descobrir a história deste drink</button>`;
  }

  return `
    <div class="historia">
      <span class="rotulo-hist">A história</span>
      <p>${h.historia}</p>
      ${h.criador ? `<p class="assinatura">— ${h.criador}</p>` : ''}
      ${h.curiosidade ? `<p class="curiosidade">${h.curiosidade}</p>` : ''}
      <ul class="ficha-drink">
        ${linha('Ocasião', h.ocasiao || ocasiaoDerivada(r))}
        ${linha('Temperatura', h.temperatura)}
        ${linha('Harmoniza com', h.harmoniza)}
        ${linha('Variações', h.variacoes)}
        ${linha('Na cultura', h.cultura)}
      </ul>
      ${h.porIA ? '<p class="dica">História escrita pelo Especialista.</p>' : ''}
    </div>`;
}

// Pede ao Especialista a história de um drink sem verbete e guarda no aparelho
async function buscarHistoriaIA(receita) {
  const chave = Store.getApiKey();
  if (!chave) return null;
  const resposta = await askExpert(chave,
    'Você é um historiador de coquetelaria. Responda SOMENTE com um objeto JSON válido, ' +
    'sem cercas de código, com as chaves: origem (cidade/país e época), criador, historia ' +
    '(2 a 3 frases, em português do Brasil, tom de bartender culto; se a origem for ' +
    'disputada, diga "conta-se que"), curiosidade (1 frase surpreendente), ocasiao, ' +
    'temperatura, harmoniza, variacoes, cultura (filme, série ou fato cultural; se não ' +
    'houver, string vazia).',
    [{ role: 'user', content: `Conte a história do drink "${receita.nome}", feito com ${receita.ing.map(i => ING_MAP[i.id]?.nome || i.id).join(', ')}.` }]);
  const m = resposta.match(/\{[\s\S]*\}/);
  if (!m) return null;
  try {
    const dados = JSON.parse(m[0]);
    const guardadas = Store.getHistorias();
    guardadas[receita.id] = { ...dados, porIA: true };
    Store.setHistorias(guardadas);
    return guardadas[receita.id];
  } catch { return null; }
}
